version: '3.8'

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    networks:
      - qdrant-network

  # Hybrid Search API with GPU support
  hybrid-search-api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: hybrid-search-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      # API Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_KEY=${API_KEY:-your-secure-api-key-here}
      
      # Qdrant Configuration
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=hybrid_search
      
      # Model Configuration
      - DENSE_MODEL=intfloat/multilingual-e5-large
      - SPARSE_MODEL=prithivida/Splade_PP_en_v1
      
      # GPU Settings for RTX 4000
      - USE_GPU=true
      - CUDA_DEVICE=0
      - BATCH_SIZE=32
      - MAX_SEQUENCE_LENGTH=512
      
      # Performance Settings
      - NUM_WORKERS=4
      - CACHE_EMBEDDINGS=true
      - EMBEDDING_CACHE_SIZE=10000
      
      # n8n Integration
      - N8N_WEBHOOK_ENABLED=true
      - N8N_WEBHOOK_TIMEOUT=30
      
      # Logging
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      
      # CORS
      - CORS_ENABLED=true
      - CORS_ORIGINS=["*"]
      
    depends_on:
      - qdrant
    networks:
      - qdrant-network
    # GPU support - uncomment if nvidia-docker is installed
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # runtime: nvidia

networks:
  qdrant-network:
    driver: bridge

volumes:
  qdrant-storage:
    driver: local
  models-cache:
    driver: local